/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peggle.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import peggle.logic.Map;

/**
 *
 * @author kj
 */
public class MapSelectionPanel extends JPanel {

    private ArrayList<JButton> mapList;
    private Map chosenMap;
    private Dimension buttonSize;
    private MyListener listener;
    
    public MapSelectionPanel() {
        this.setSize(MainFrame.WIDTH_PANEL, MainFrame.HEIGHT_PANEL);
        this.setLayout(null);
        this.setBackground(Color.lightGray);
        mapList = new ArrayList<>();
        buttonSize = new Dimension(80 * MainFrame.SCALE, 80 * MainFrame.SCALE);
        listener = new MyListener();
        //chosenMap = new Map();
    }

    public void start() {
        
        try {
            Files.newDirectoryStream(Paths.get("./maps/"), path -> path.toString().endsWith(".pgl")).forEach(filePath -> mapList.add(new JButton(filePath.toString().substring(7))));
          
        } catch (IOException ex) {
            Logger.getLogger(MapSelectionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int maxButtonPerColumn = 4;
        int columnCount = 0;
        int rowCount = 0;
        
        for(JButton btn : mapList) {
            
            if (columnCount < maxButtonPerColumn) {
                columnCount++;
            }
            else {
                columnCount = 1;
                rowCount++;
            }
            //btn.setBounds((MainFrame.WIDTH_PANEL-buttonSize.width)/3, (MainFrame.HEIGHT_PANEL-buttonSize.height)/3, buttonSize.width, buttonSize.height);
            btn.setBounds(((MainFrame.WIDTH_PANEL-buttonSize.width)*columnCount)/5, (rowCount*90*MainFrame.SCALE + 40), buttonSize.width, buttonSize.height);
            //btn.setBounds((MainFrame.WIDTH_PANEL-buttonSize.width)*columnCount/maxButtonPerColumn, (MainFrame.HEIGHT_PANEL-buttonSize.height)/**mapList.indexOf(btn)*/*rowCount/mapList.size(), buttonSize.width, buttonSize.height);
            btn.addMouseListener(listener);
            this.add(btn);
        }
    }
    
    public Map getChosenMap() {
        return chosenMap;
    }
    
    public void clearMapList() {
        for(JButton btn : mapList){
            btn.setVisible(false);
        }
        repaint();
        mapList.clear();
    }
    
    protected static Map readMap(String pMapName) {
        Map returnMap = null;
        FileInputStream fis;
        ObjectInputStream ois;
        
        try {
            fis = new FileInputStream("./maps/" + pMapName);
            ois = new ObjectInputStream(fis);
            returnMap = (Map) ois.readObject();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MapSelectionPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MapSelectionPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MapSelectionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return returnMap;
    }
    
    private class MyListener extends MouseAdapter {
        
       @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            JButton clickedBtn = (JButton) e.getSource();
            Map tempMap;
            
            for(JButton btn : mapList) {
                if(clickedBtn.equals(btn)) {
                    tempMap = readMap(btn.getText());
                    if(tempMap != null) {
                        chosenMap = tempMap;
                        MainFrame.showPanel(MainFrame.START_GAME);
                        
                    }
                    else {
                        MainFrame.showPanel(MainFrame.WELCOME);
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
