/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peggle.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;

/**
 *
 * @author kj
 */

public class WelcomePanel extends javax.swing.JPanel {

    private JButton buttonSolo;
    private JButton buttonDuel;
    private JButton buttonExit;
    private Dimension buttonSize;
    
    private MyListener listener;
            
            
    public WelcomePanel() {
        this.setSize(MainFrame.WIDTH_PANEL, MainFrame.HEIGHT_PANEL);
        this.setLayout(null);
        this.setBackground(Color.lightGray);
        
        listener = new MyListener();
        
        buttonSize = new Dimension(200 * MainFrame.SCALE, 80 * MainFrame.SCALE);
        
        buttonSolo = new JButton("Solo");
        buttonSolo.setBounds((MainFrame.WIDTH_PANEL-buttonSize.width)/2, (MainFrame.HEIGHT_PANEL-buttonSize.height)/4, buttonSize.width, buttonSize.height);
        buttonSolo.addMouseListener(listener);
        this.add(buttonSolo);
        
        buttonDuel = new JButton("Duel");
        buttonDuel.setBounds((MainFrame.WIDTH_PANEL-buttonSize.width)/2, (MainFrame.HEIGHT_PANEL-buttonSize.height)*2/4, buttonSize.width, buttonSize.height);
        buttonDuel.addMouseListener(listener);
        this.add(buttonDuel);
        
        buttonExit = new JButton("Esci");
        buttonExit.setBounds((MainFrame.WIDTH_PANEL-buttonSize.width)/2, (MainFrame.HEIGHT_PANEL-buttonSize.height)*3/4, buttonSize.width, buttonSize.height);
        buttonExit.addMouseListener(listener);
        this.add(buttonExit);
        
    }

    private class MyListener extends MouseAdapter {
        
       @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            JButton btn = (JButton) e.getSource();
            
            if(btn.equals(buttonSolo)) MainFrame.showPanel(MainFrame.GAME_SOLO);
            if(btn.equals(buttonDuel)) MainFrame.showPanel(MainFrame.GAME_DUEL);
            if(btn.equals(buttonExit)) System.exit(0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
